services:
  mssql:
    image: docker.io/mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_ENABLE_FTS: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  typesense:
    image: docker.io/typesense/typesense:27.1
    environment:
      TYPESENSE_API_KEY: "devkey123"
      TYPESENSE_DATA_DIR: "/data"
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data

volumes:
  mssql_data:
  typesense_data:
