USE ResearchPublications;
GO

-- ── Authors ───────────────────────────────────────────────────────────────
INSERT INTO Authors (FullName, Email) VALUES
    ('Juliet Ramsay', 'julietdmramsay@hotmail.com'),
    ('Feng Han',      'franhanf@gmail.com');
GO

-- ── Publications ─────────────────────────────────────────────────────────
INSERT INTO Publications (Title, Abstract, Body, Keywords, Year, DOI, CitationCount, PdfFileName) VALUES
(
    'Space is Not Nothing: Heritage Aesthetics and the Struggle for Space',
    'The paper explores government encouraged industrial developments in the name of climate change mitigation and the impacts on the aesthetic and social values of rural cultural landscapes and rural lifestyles. The squandering of space and the disruption of spatial scale is also considered and discussed with regard to cultural landscapes. Examples of urban and rural landscapes are presented with an analysis of the effectiveness of heritage listings and the at times unjust and arduous plight forced on rural communities by development impacts.',
    'Space is an essential element in reading cultural landscapes, be it a part of the smallest garden or the largest designed landscape or the intimacy and expanses of countryside and nature. Aristotle described space as the container of all objects while Isaac Newton proposed the notion of ''absolute space'' -- that space is an entity that frames and contains all material objects. Space can be unlimited, infinite, indefinite or subtly defined. Space is where we accumulate our intimate experience through time and where place is created through myths, legends and emotional attachment to land. Space also presents the visibility of the creation of space through which we appreciate the aesthetics of structures or landforms or sounds. Space therefore gives us the dimension to read, understand and enjoy a place. Space and aesthetics are indivisible. Colors, size, lines, patterns ethereal and ephemeral moments in space give rise to our metaphysical imagination. Space can be physical, social and symbolic and along with aesthetics is a significant element of landscapes.
The Xi''an Declaration on the Conservation of the Setting of Heritage Structures, Sites and Areas (2005) initiated wider recognition of the importance of the spatial settings of World Heritage Places. Apart from the value of space as a setting there is the value of space as a backdrop -- the ability to recall the attached emotions and collective memories through history by experiencing and appreciating the silhouettes of hills rolling across a landscape, patterns of hills of different hues, the rugged form of mountain ranges and the skylines of cities.
West Lake, Hangzhou, inscribed in the World Heritage List in 2011 with a history of 2,100 years, is known as ''the Heaven on Earth'' in China. It is a national cultural icon and a representative of a living cultural landscape underpinned by Chinese philosophy and aesthetics on the relationship between human beings and nature. West Lake is a miraculous space with multiple layers of meanings. Hills embrace the lake on three sides; the city proper lies to the east. The West Lake appears natural with cultural construction harmoniously decorated around it. However, this intoxicating ''natural'' landscape is not natural; rather, it is culturally constructed according to Chinese philosophical and landscape aesthetic principles. West Lake was an open social space where emperors, scholars, citizens, officials, the successful, the failures and the religious were gathering. It was a collective work by multiple social groups. Today, West Lake is successfully evolving and travelling there is still something that one must do in a lifetime as a Chinese person.
Canberra, Australia''s national capital, famously manifests a city design by the American architect and landscape architect Walter Burley Griffin. The key components of the plan were the land and water axes that connect local mountains and hills with a central city lake while a triangular geometric pattern bisected by the axes sets the framework for the national capital. The vista is the captured axial view that engages the eye, sweeps down from Parliament House, fans out at the lake and then sweeps up at the grassed terraces to terminate in the forested conical Mount Ainslie. Lake Burley Griffin is the other critical spatial element, created by damming a small river, creating a water system flowing through the centre of the city. The critical ''loose space'' of the grassed terraces is used by the community for recreation events, cultural events and celebrations, and is now under threat from proposed large stone war memorials that will impact the space and be eye stoppers in the vista.
The exploitation of rural land spaces is happening not just in China and Australia but everywhere. Key issues are urbanization, abandoned land, suburban expansion, glass housing of market gardens, industrial scale mono-crop farming, plantations, sourcing of wind power, minerals and natural gas. China''s rural landscape was a traditional aesthetic objective but today is especially under threat of rapid urbanization, with more than 13 million farmers leaving their land and moving into cities every year. Wind turbines, now over 100m high, tower over fields and farms and stand atop ridges, appropriating the valued space of rural setting landscapes. Community actions against wind-farm installations are unfairly labelled as the ''nimby'' (not in my backyard) without appreciating that communities have heart-felt love of their landscape for a multitude of aesthetic and emotional reasons.
Heritage practitioners need to describe the aesthetic quality of spaciousness: the colours and textures of the space; the character of how the space is delineated such as features that edge the space; terminal features of a space; the base plane or planes; how water works in a space; the aesthetic evocations of a space; views in, views out, major viewpoints; sounds of the space -- natural sounds, discordant sounds, quietness; and how people and wildlife use the space. Apart from describing a space thoroughly, another effective measure is to interpret the space in an engaging way so that its spectrum of values is understood and appreciated.
Spaces as components of cultural heritage places contribute to cultural capital. Heritage spaces are part of a cultural system and failure to recognise the essential visual and non-visual qualities as well as conserve and manage such places could put a precinct or area in peril and cause loss of community well-being, a loss of associational value, as well as loss of economic output. Space, particularly urban space, is precious and highly sought after by developers, and now rural space is also targeted. Heritage landscape spaces will frequently be contested. Space is a non-renewable resource. Spaces are the settings for the existence of life. Space is not nothing.',
    'heritage aesthetics, cultural landscapes, space, rural landscapes, West Lake, Hangzhou, Canberra, heritage listing, spatial values, cultural capital',
    2011,
    NULL,
    15,
    'I-2-Article4_Ramsay_Han.pdf'
);
GO

-- ── Publication–Author links ──────────────────────────────────────────────
-- Publication 1: Ramsay, Han
INSERT INTO PublicationAuthors VALUES (1, 1), (1, 2);
GO
